name: Scaffold project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create folders & placeholder files
        run: |
          mkdir -p public assets/css assets/js src/pages/trading src/pages/nemovitosti src/pages/investice
          touch public/.keep assets/css/.keep assets/js/.keep
          # vytvoř minimální index.html pokud chybí
          if [ ! -f index.html ]; then
            cat > index.html <<'EOF'
            <!doctype html>
            <html lang="cs"><head><meta charset="utf-8"><title>StrategyMind</title></head>
            <body>Projekt připraven. 👋</body></html>
            EOF
          fi

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Scaffold project structure"
            git push
          else
            echo "No changes to commit"
          fi
