name: Scaffold project

on:
  workflow_dispatch:

# Důležité: workflow musí mít právo zapisovat do repa
permissions:
  contents: write

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folders
        run: |
          set -e
          mkdir -p public assets/css assets/js src/pages/trading src/pages/nemovitosti src/pages/investice
          touch public/.gitkeep assets/css/.gitkeep assets/js/.gitkeep \
                src/pages/trading/.gitkeep src/pages/nemovitosti/.gitkeep src/pages/investice/.gitkeep

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Scaffold project structure"
            git push
          else
            echo "No changes to commit."
          fi
